name: Dry run

on:
  push:
    branches: [ main ]
    paths:
    - 'automation/pyproject.toml'
    - 'automation/poetry.lock'
    - '**.py'
    - '.github/workflows/dry-run.yml'

  pull_request:
    branches: [ "main" ]
    paths:
    - 'automation/pyproject.toml'
    - 'automation/poetry.lock'
    - '**.py'
    - '.github/workflows/dry-run.yml'

jobs:
  process-translations:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Poetry
      run: pipx install poetry

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.*
        cache: "poetry"
        cache-dependency-path: automation/poetry.lock

    - name: Install library and dependencies
      run: |
        cd automation
        poetry install --no-interaction --no-dev

    - name: Dry run automation scripts
      run: |
        cd automation
        poetry run files_by_resource ../translations ../
