name: Pull translations from transifex

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pull-translations:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install transifex client
      run: |
        curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash

    - name: Pull translations
      env:
        TX_TOKEN: ${{ secrets.TX_TOKEN }}
      run: |
        ./tx pull -f -a

    - name: Push changes to the repository
      uses: EndBug/add-and-commit@v9.1.1
      with:
        author_name: github-actions[bot]
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        add: translations

  trigger-translation-artifacts-autobuild:
    runs-on: ubuntu-latest
    needs: pull-translations
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT }}
        repository: dfint/autobuild
        event-type: update
