name: Pull translations from transifex

on:
  schedule:
    - cron: "0 0 * * *"  # Run every day at 03:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install transifex client
      run: |
        python3 -m pip install --upgrade pip
        pip3 install transifex-client

    - name: Pull translations
      run: |
        export TX_TOKEN=${{ secrets.TX_TOKEN }}
        tx pull --f --parallel

    - name: Push changes to the repository
      uses: EndBug/add-and-commit@v7.0.0
      with:
        author_name: 'github-actions[bot]'
        author_email: 'github-actions[bot]@localhost'
