name: Pull translations from transifex

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install transifex client
      run: |
        python -m pip install --upgrade pip
        pip install transifex-client
    - name: Pull translations
      run: |
        export TX_TOKEN=${{ secrets.TX_TOKEN }}
        tx pull -a
